// Copyright © 2026 Aerospace Corporation
// SPDX-License-Identifier: LGPL-3.0-or-later

/**
 * @file spacecop_events.h
 * @brief Event message ID definitions for SpaceCop IDS application
 *
 * This header defines all Event Services (EVS) event IDs used by the SpaceCop
 * application. Event IDs are used to uniquely identify different types of
 * events generated by the application for logging, telemetry, and ground
 * system display.
 *
 * **Event ID Organization:**
 * Event IDs are grouped by functional area with reserved ranges:
 * - 0-9:   Standard application lifecycle events
 * - 10-19: Ground command processing events
 * - 20-29: Device-specific command events
 * - 30-39: Telemetry request events
 * - 40-49: Hardware protocol events
 *
 * **Event Types:**
 * Each event ID is used with a specific event type:
 * - INFORMATION: Normal operations, successful commands
 * - ERROR: Error conditions, failed operations
 * - CRITICAL: Severe errors requiring immediate attention
 * - DEBUG: Development/debugging information
 *
 * **Usage:**
 * Event IDs are passed to CFE_EVS_SendEvent() along with event type and
 * formatted message:
 * @code
 * CFE_EVS_SendEvent(SPACECOP_STARTUP_INF_EID, 
 *                   CFE_EVS_EventType_INFORMATION,
 *                   "SPACECOP App Initialized. Version %d.%d.%d.%d",
 *                   major, minor, revision, mission);
 * @endcode
 *
 * **Event Filtering:**
 * Ground systems can filter events by ID to control which messages are
 * displayed or logged. Critical events should never be filtered.
 *
 * @note Event IDs must be unique within the application
 * @note Event ID 0 is reserved and should not be used
 * @note New event IDs should be added to appropriate range
 *
 * @see CFE_EVS_SendEvent()
 */

#ifndef _SPACECOP_EVENTS_H_
#define _SPACECOP_EVENTS_H_

/*=======================================================================================
** Standard Application Event IDs (0-9)
** 
** Events related to application lifecycle, initialization, and core operations.
**=======================================================================================*/

/**
 * @brief Reserved event ID (do not use)
 * 
 * Event ID 0 is reserved by convention and should not be used for any events.
 */
#define SPACECOP_RESERVED_EID              0

/**
 * @brief Application startup/initialization event
 * 
 * Sent when the SpaceCop application successfully completes initialization.
 * Includes version information for ground system display.
 * 
 * **Event Type:** INFORMATION
 * 
 * **Typical Message:**
 * "SPACECOP App Initialized. Version X.X.X.X"
 * 
 * @see SPACECOP_AppInit()
 */
#define SPACECOP_STARTUP_INF_EID           1

/**
 * @brief Command length verification error
 * 
 * Sent when a received command packet length does not match the expected
 * length for the command code. Indicates malformed or corrupted command.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "Invalid msg length: ID = 0xXXXX, CC = X, Len = X, Expected = X"
 * 
 * @see SPACECOP_VerifyCmdLength()
 */
#define SPACECOP_LEN_ERR_EID               2

/**
 * @brief Software Bus pipe creation error
 * 
 * Sent when CFE_SB_CreatePipe() fails during initialization. Indicates
 * system resource exhaustion or configuration error.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "Error Creating SB Pipe, RC=0xXXXXXXXX"
 * 
 * @see SPACECOP_AppInit()
 */
#define SPACECOP_PIPE_ERR_EID              3

/**
 * @brief Ground command subscription error
 * 
 * Sent when CFE_SB_Subscribe() fails for SPACECOP_CMD_MID during
 * initialization. Prevents reception of ground commands.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "Error Subscribing to HK Gnd Cmds, MID=0xXXXX, RC=0xXXXXXXXX"
 * 
 * @see SPACECOP_AppInit()
 */
#define SPACECOP_SUB_CMD_ERR_EID           4

/**
 * @brief Housekeeping request subscription error
 * 
 * Sent when CFE_SB_Subscribe() fails for SPACECOP_REQ_HK_MID during
 * initialization. Prevents sending housekeeping telemetry.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "Error Subscribing to HK Request, MID=0xXXXX, RC=0xXXXXXXXX"
 * 
 * @see SPACECOP_AppInit()
 */
#define SPACECOP_SUB_REQ_HK_ERR_EID        5

/**
 * @brief Command packet processing error
 * 
 * Sent when an unrecognized Message ID is received on the command pipe.
 * Indicates invalid command routing or corrupted message.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "SPACECOP: Invalid command packet, MID = 0xXXXX"
 * 
 * @see SPACECOP_ProcessCommandPacket()
 */
#define SPACECOP_PROCESS_CMD_ERR_EID       6

/**
 * @brief Table operation error
 * 
 * Sent when table registration, loading, or address acquisition fails.
 * Indicates file system error or corrupted table file.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "SPACECOP Can't register/load/get table status X"
 * 
 * @see SPACECOP_AppInit()
 */
#define SPACECOP_TBL_ERR_EID       		   7

/*=======================================================================================
** Standard Command Event IDs (10-19)
** 
** Events related to ground command processing and validation.
**=======================================================================================*/

/**
 * @brief Invalid command code error
 * 
 * Sent when an unrecognized command code is received for SPACECOP_CMD_MID.
 * Indicates ground system error or corrupted command.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "SPACECOP: Invalid command code for packet, MID = 0xXXXX, cmdCode = 0xXX"
 * 
 * @see SPACECOP_ProcessGroundCommand()
 */
#define SPACECOP_CMD_ERR_EID               10

/**
 * @brief NOOP command received
 * 
 * Sent when a NOOP (No Operation) command is successfully received and
 * validated. Used to verify command interface is operational.
 * 
 * **Event Type:** INFORMATION
 * 
 * **Typical Message:**
 * "SPACECOP: NOOP command received"
 * 
 * @see SPACECOP_ProcessGroundCommand()
 */
#define SPACECOP_CMD_NOOP_INF_EID          11

/**
 * @brief Reset counters command received
 * 
 * Sent when a RESET COUNTERS command is successfully received and validated.
 * CommandCount and CommandErrorCount are reset to zero.
 * 
 * **Event Type:** INFORMATION
 * 
 * **Typical Message:**
 * "SPACECOP: RESET counters command received"
 * 
 * @see SPACECOP_ProcessGroundCommand()
 * @see SPACECOP_ResetCounters()
 */
#define SPACECOP_CMD_RESET_INF_EID         12

/**
 * @brief Enable command received
 * 
 * Sent when an ENABLE command is successfully received and validated.
 * Used to enable specific monitoring features.
 * 
 * **Event Type:** INFORMATION
 * 
 * **Typical Message:**
 * "SPACECOP: Enable command received"
 * 
 * @see SPACECOP_ProcessGroundCommand()
 */
#define SPACECOP_CMD_ENABLE_INF_EID        13

/**
 * @brief Monitor enabled successfully
 * 
 * Sent when a specific monitor or detection feature is successfully enabled.
 * 
 * **Event Type:** INFORMATION
 * 
 * **Typical Message:**
 * "SPACECOP: Monitor X enabled"
 */
#define SPACECOP_ENABLE_INF_EID            14

/**
 * @brief Monitor enable error
 * 
 * Sent when enabling a monitor or detection feature fails.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "SPACECOP: Failed to enable monitor X"
 */
#define SPACECOP_ENABLE_ERR_EID            15

/**
 * @brief Disable command received
 * 
 * Sent when a DISABLE command is successfully received and validated.
 * Used to disable specific monitoring features.
 * 
 * **Event Type:** INFORMATION
 * 
 * **Typical Message:**
 * "SPACECOP: Disable command received"
 * 
 * @see SPACECOP_ProcessGroundCommand()
 */
#define SPACECOP_CMD_DISABLE_INF_EID       16

/**
 * @brief Monitor disabled successfully
 * 
 * Sent when a specific monitor or detection feature is successfully disabled.
 * 
 * **Event Type:** INFORMATION
 * 
 * **Typical Message:**
 * "SPACECOP: Monitor X disabled"
 */
#define SPACECOP_DISABLE_INF_EID           17

/**
 * @brief Monitor disable error
 * 
 * Sent when disabling a monitor or detection feature fails.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "SPACECOP: Failed to disable monitor X"
 */
#define SPACECOP_DISABLE_ERR_EID           18

/*=======================================================================================
** Device-Specific Command Event IDs (20-29)
** 
** Events related to device-specific commands and configuration.
**=======================================================================================*/

/**
 * @brief Configuration command received
 * 
 * Sent when a device-specific configuration command is successfully processed.
 * 
 * **Event Type:** INFORMATION
 * 
 * **Typical Message:**
 * "SPACECOP: Configuration updated"
 */
#define SPACECOP_CMD_CONFIG_INF_EID        20

/**
 * @brief CPU-related command event
 * 
 * Sent for CPU-specific commands or operations.
 * 
 * **Event Type:** INFORMATION or ERROR (context-dependent)
 * 
 * **Typical Message:**
 * "SPACECOP: CPU command processed"
 */
#define SPACECOP_CMD_CPU_EID			   21

/*=======================================================================================
** Standard Telemetry Event IDs (30-39)
** 
** Events related to telemetry request processing.
**=======================================================================================*/

/**
 * @brief Device telemetry request error
 * 
 * Sent when processing a device-specific telemetry request fails.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "SPACECOP: Invalid command code for packet, MID = 0xXXXX, cmdCode = 0xXX"
 * 
 * @see SPACECOP_ProcessTelemetryRequest()
 */
#define SPACECOP_DEVICE_TLM_ERR_EID        30

/**
 * @brief Housekeeping request processing error
 * 
 * Sent when processing a housekeeping telemetry request fails.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "SPACECOP: HK request processing error"
 * 
 * @see SPACECOP_ProcessTelemetryRequest()
 */
#define SPACECOP_REQ_HK_ERR_EID            31

/*=======================================================================================
** Device-Specific Telemetry Event IDs (32-39)
** 
** Events related to device-specific telemetry operations.
**=======================================================================================*/

/**
 * @brief Device data request error
 * 
 * Sent when a device-specific data request fails or returns invalid data.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "SPACECOP: Device data request failed"
 */
#define SPACECOP_REQ_DATA_ERR_EID          32

/*=======================================================================================
** Hardware Protocol Event IDs (40-49)
** 
** Events related to hardware interface initialization and communication.
**=======================================================================================*/

/**
 * @brief UART initialization error
 * 
 * Sent when UART (serial port) initialization fails. May indicate hardware
 * failure or configuration error.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "SPACECOP: UART initialization failed"
 * 
 * @note Not currently used - reserved for future hardware interface support
 */
#define SPACECOP_UART_INIT_ERR_EID         40

/**
 * @brief UART close error
 * 
 * Sent when closing a UART (serial port) fails during shutdown.
 * 
 * **Event Type:** ERROR
 * 
 * **Typical Message:**
 * "SPACECOP: UART close failed"
 * 
 * @note Not currently used - reserved for future hardware interface support
 */
#define SPACECOP_UART_CLOSE_ERR_EID        41

#endif /* _SPACECOP_EVENTS_H_ */